# SELECT  A.PRODUCT_ID,	A.PRODUCT_NAME,	SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT A
# JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
# WHERE PRODUCE_DATE LIKE '2022-05%'
# GROUP BY PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;

select a.PRODUCT_ID,PRODUCT_NAME, sum( PRICE * AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT a
join FOOD_ORDER b on a.PRODUCT_ID = b.PRODUCT_ID
where PRODUCE_DATE like '2022-05%'
group by PRODUCT_ID
order by TOTAL_SALES desc, PRODUCT_ID asc;













