# SELECT A.ANIMAL_ID,	A.ANIMAL_TYPE,	A.NAME
# FROM ANIMAL_INS A
# JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE A.SEX_UPON_INTAKE LIKE 'Intact%' AND (B.SEX_UPON_OUTCOME LIKE 'Spayed%' OR B.SEX_UPON_OUTCOME LIKE 'Neutered%')
# ORDER BY ANIMAL_ID;

select a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
from ANIMAL_INS a
join ANIMAL_OUTS b on a.ANIMAL_ID = b.ANIMAL_ID
where SEX_UPON_INTAKE like 'Intact%' and (SEX_UPON_OUTCOME like 'Spayed%' or SEX_UPON_OUTCOME like 'Neutered%')
order by ANIMAL_ID;












