# SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE A
# JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
# GROUP BY REVIEW_TEXT
# HAVING COUNT(A.MEMBER_ID) = MAX(A.MEMBER_ID)


select MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
from MEMBER_PROFILE a
join REST_REVIEW b on a.MEMBER_ID = b.MEMBER_ID
where a.MEMBER_ID =
(
    select MEMBER_ID
    from REST_REVIEW
    group by MEMBER_ID
    order by count(MEMBER_ID) desc
    limit 1   
)
order by REVIEW_DATE asc, REVIEW_TEXT asc;

